//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gh0st.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GH0STTYPE                   129
#define IDD_BUILD                       131
#define IDR_MENU_REPORT                 131
#define IDD_FILE                        132
#define IDR_LIST                        133
#define IDC_DRAG                        134
#define IDC_MUTI_DRAG                   135
#define IDC_CURSOR3                     136
#define IDC_CURSOR4                     137
#define IDD_SETTINGS                    140
#define IDD_UPDATE_DLG                  144
#define IDR_FILEMANAGER                 146
#define IDR_TOOLBAR1                    147
#define IDB_TOOLBAR                     149
#define IDB_TOOLBAR_ENABLE              149
#define IDR_TOOLBAR233                  154
#define IDR_TOOLBAR2555                 155
#define IDR_TOOLBAR2                    155
#define IDR_LOCAL_VIEW                  156
#define IDR_REMOTE_VIEW                 157
#define IDB_TOOLBAR_DISABLE             158
#define IDD_TRANSFERMODE_DLG            159
#define IDD_SCREENSPY                   160
#define IDD_DOWNEXEC                    162
#define IDD_WEBCAM                      163
#define IDI_WEBCAM                      164
#define IDB_ARROWDOWN                   165
#define IDB_ARROWUP                     166
#define IDD_KEYBOARD                    167
#define IDD_NEWFOLDER                   168
#define IDD_SYSTEM                      169
#define IDR_PSLIST                      170
#define IDD_SHELL                       171
#define IDR_BSS                         173
#define IDI_CMDSHELL                    177
#define IDI_KEYBOARD                    178
#define IDI_SYSTEM                      179
#define IDC_DOT                         182
#define IDR_MINIMIZE                    183
#define IDD_AUDIO                       184
#define IDI_AUDIO                       185
#define IDB_SPLASH                      186
#define IDB_BITMAP_SCREEN               187
#define IDB_BITMAP_FILEMANAGER          188
#define IDB_BITMAP_KEYBORD              189
#define IDB_BITMAP_COMMAND              190
#define IDB_BITMAP_SYSMANAGER           191
#define IDB_BITMAP_VEDIO                192
#define IDB_BITMAP_SOUND                193
#define IDB_BITMAP_ABOUT                194
#define IDB_BITMAP_EXIT                 195
#define IDB_BITMAP_CREATESERVER         196
#define IDB_BITMAP_ATTACK               197
#define IDB_BITMAP_SKIN                 198
#define IDD_CHANGESKIN_DIALGO           199
#define IDB_BITMAP_UPDATE               200
#define IDB_BITMAP_SIFT                 201
#define IDD_ATTACK_DIALOG               202
#define IDD_FLOWATTACK_DIALOG           203
#define IDD_CUSTOMATTACK_DIALOG         204
#define IDI_ICON_DDOS                   206
#define IDD_ADD_USER                    208
#define IDD_SIFT_HOST                   210
#define IDI_ICON_SIFT                   211
#define IDD_BTACK_DIALOG                212
#define IDR_BATCH_MENU                  214
#define IDD_BUILDDIALOG                 215
#define IDD_CONFIG_DIALOG               216
#define IDI_ICON_SETING                 217
#define IDR_WAVE1                       219
#define IDR_WAVE2                       220
#define IDD_LOGON_DIALOG                221
#define IDB_BITMAP_LOGON                222
#define IDB_BITMAP_INFO                 223
#define IDD_MIANZESHENGMING             225
#define IDB_BITMAP_TOOLS                226
#define IDD_TOOLS_DIALOG                227
#define IDI_ICON_TOOL                   228
#define IDI_ICON_MD5                    229
#define IDR_BSS1                        231
#define IDD_BUGSUBMIT_DIALOG            232
#define IDB_BITMAP_SUBMIT               233
#define IDD_CHAT_DIALOG                 234
#define IDD_CLOSE_DIALOG                235
#define IDR_BSS2                        237
#define IDD_COMMUNIQUE_DIALOG           238
#define IDD_PLUGIN_DIALOG               239
#define IDI_PLUGIN                      239
#define IDR_PLUGIN                      240
#define IDR_SKIN1                       241
#define IDI_EVENT                       242
#define IDD_SKIN_COLOUR                 243
#define IDR_MENU_LOG_LIST               282
#define IDC_LIST_TARGET                 1002
#define IDC_TARGET_WEB                  1003
#define IDC_ATTCKPORT                   1004
#define IDC_LIST_REMOTE                 1005
#define IDC_THREADNUMS                  1005
#define IDC_LIST_LOCAL                  1006
#define IDC_LOCAL_PATH                  1007
#define IDC_HOSTNUMS                    1007
#define IDC_REMOTE_PATH                 1008
#define IDC_SLIDER_THREAD               1008
#define IDC_STATIC_REMOTE               1009
#define IDC_ATTACKTIMES                 1009
#define IDC_CONFIRM                     1010
#define IDC_SLIDER_TIME                 1010
#define IDC_COMBO_FTPIP                 1010
#define IDC_PORT                        1011
#define IDC_LISTEN_PORT                 1011
#define IDC_SPIN_NUM                    1011
#define IDC_EDIT_FTPIP                  1011
#define IDC_OVERWRITE                   1012
#define IDC_CONNECT_MAX                 1012
#define IDC_NEWAUTO                     1012
#define IDC_EDIT_FTPPORT                1012
#define IDC_ADDITION                    1013
#define IDC_SELECTHOST                  1013
#define IDC_COMBO_DNSIP                 1013
#define IDC_JUMP                        1014
#define IDC_ADDTASK                     1014
#define IDC_SEND_RATE                   1014
#define IDC_COMBO_FTPPORT               1014
#define IDC_OVERWRITE_ALL               1015
#define IDC_COMBO_MODEL                 1015
#define IDC_ADDITION_ALL                1016
#define IDC_STARTVAR                    1016
#define IDC_SPIN_RATE                   1016
#define IDC_JUMP_ALL                    1017
#define IDC_ENDVAR                      1017
#define IDC_CANCEL                      1018
#define IDC_TIPS                        1019
#define IDC_STATIC_TIP                  1020
#define IDC_URL                         1021
#define IDC_EDIT_DECIMAL                1021
#define IDC_ENCODE                      1022
#define IDC_DNS_STRING                  1022
#define IDC_EDIT_HEX                    1022
#define IDC_REMOTE_HOST                 1023
#define IDC_REMOTE_PORT                 1024
#define IDC_STATIC_2                    1024
#define IDC_EDIT_FTPUSER                1024
#define IDC_PROXY_HOST                  1025
#define IDC_STATIC_1                    1025
#define IDC_EDIT_FTPPASS                1025
#define IDC_PROXY_PORT                  1026
#define IDC_STATIC_3                    1026
#define IDC_FTPURL                      1026
#define IDC_PROXY_USER                  1027
#define IDC_STATIC_4                    1027
#define IDC_BTN_FTPUPDATE               1027
#define IDC_PROXY_PASS                  1028
#define IDC_STATIC_6                    1028
#define IDC_EDIT_DNSUSER                1028
#define IDC_EDIT                        1029
#define IDC_STATIC_7                    1029
#define IDC_EDIT_DNSPASS                1029
#define IDC_RESETPORT                   1030
#define IDC_STATIC_8                    1030
#define IDC_EDIT_DNSDOMAIN              1030
#define IDC_FOLDERNAME                  1031
#define IDC_STATIC_9                    1031
#define IDC_BTN_DNSUPDATE               1031
#define IDC_STATIC_10                   1032
#define IDC_STATIC_11                   1033
#define IDC_LIST_PROCESS                1034
#define IDC_TAB                         1035
#define IDC_EDIT_TIP                    1035
#define IDC_LIST_WINDOWS                1036
#define IDC_STATIC_20                   1036
#define IDC_LIST_DIALUPASS              1037
#define IDC_START_ATTACK                1037
#define IDC_BUILD                       1038
#define IDC_START_STOP                  1038
#define IDC_RANDOM                      1039
#define IDC_CONNECT_AUTO                1040
#define IDC_STATIC_VER                  1041
#define IDC_ENABLE_HTTP                 1043
#define IDC_CHECK_AUTH                  1048
#define IDC_CHECK_PROXY                 1049
#define IDC_TEST_PROXY                  1050
#define IDC_TEST_MASTER                 1051
#define IDC_SYSTEM_TIPS                 1052
#define IDC_DISABLE_POPTIPS             1053
#define IDC_SEND_LOCALAUDIO             1054
#define IDC_SAVEAS_DEFAULT              1054
#define IDC_SERVICE_DISPLAYNAME         1058
#define IDC_SERVICE_DESCRIPTION         1059
#define IDC_SLIDER1                     1060
#define IDC_SLIDER2                     1061
#define IDC_SLIDER3                     1062
#define IDC_EDIT1                       1063
#define IDC_EDIT_DATA                   1063
#define IDC_EDIT_URL                    1063
#define IDC_LINSTEN_PORT                1063
#define IDC_USERNAME                    1063
#define IDC_SERVERNAME                  1063
#define IDC_EDIT2                       1064
#define IDC_DDOS_ATTACK                 1064
#define IDC_EDIT_TIME                   1064
#define IDC_MAX_CONNECT                 1064
#define IDC_PASSWORD                    1064
#define IDC_SERVERDISPLAY               1064
#define IDC_EDIT3                       1065
#define IDC_STATIC_ABOUT                1065
#define IDC_SERVERDESCRIPT              1065
#define IDC_EDIT_PATH                   1065
#define IDC_CHECK_TIME                  1065
#define IDC_RADIO1                      1066
#define IDC_OMD3                        1066
#define IDC_RADIO2                      1067
#define IDC_CMD5                        1067
#define IDC_RADIO3                      1068
#define IDC_RADIO4                      1069
#define IDC_RADIO5                      1070
#define IDC_RADIO6                      1071
#define IDC_RADIO7                      1072
#define IDC_RADIO8                      1073
#define IDC_EDIT_pass                   1073
#define IDC_SIFT_HOST                   1074
#define IDC_RADIO10                     1074
#define IDC_PROGRESS1                   1075
#define IDC_RADIO11                     1075
#define IDC_SET_SKIN                    1075
#define IDC_SHOWRESULT                  1076
#define IDC_RADIO12                     1076
#define IDC_BUTTON2                     1077
#define IDC_RADIO13                     1077
#define IDC_EDIT_user                   1077
#define IDC_LIST1                       1078
#define IDC_BUTTON_SAVEAS               1078
#define IDC_RADIO9                      1078
#define IDC_EDIT_admin                  1078
#define IDC_COMBO1                      1079
#define IDC_SELECTICON                  1079
#define IDC_ADDBATCH                    1080
#define IDC_SPIN1                       1081
#define IDC_AUTO_CONNECT                1082
#define IDC_BUTTON_APPLY                1083
#define IDC_CLOSE_TIPS                  1084
#define IDC_CLOSE_ANIMATE               1085
#define IDC_CLOSE_TOTUOPAN              1086
#define IDC_OPEN_SOUND                  1087
#define IDC_STATIC_3322                 1087
#define IDC_BUTTON1                     1088
#define IDC_LOGON                       1088
#define IDC_CLOSE_APPMENT               1088
#define IDC_STATIC_FTP                  1088
#define IDC_CHECK1                      1089
#define IDC_REMEMBER                    1089
#define IDC_CHECK_URL                   1089
#define IDC_BUTTON3                     1089
#define IDC_CHECK2                      1090
#define IDC_AUTO_LOGON                  1090
#define IDC_STOP                        1090
#define IDC_BUTTON_STOP                 1090
#define IDC_FILENAME                    1091
#define IDC_CHECK_SELECT                1091
#define IDC_BUTTON4                     1091
#define IDC_FILEATTRIBUTE               1092
#define IDC_SHOWTIPS                    1093
#define IDC_DNS                         1094
#define IDC_URLADDR                     1095
#define IDC_FILESUFFIEX                 1097
#define IDC_DIRECTORY                   1098
#define IDC_TEST                        1099
#define IDC_LIST2                       1100
#define IDC_ICONS                       1101
#define IDC_SELECTFILE                  1102
#define IDC_EDIT_TIME1                  1103
#define IDC_STATIC_COUNT                1104
#define IDC_START                       1105
#define IDC_CHECK3                      1106
#define IDC_COUNT_LINES                 1107
#define IDC_BUTTON_START                1108
#define IDC_CHECK_AUTO                  1109
#define IDC_EDIT_TEXT                   1110
#define IDC_EXIT                        1110
#define IDC_ONLINE_MARK                 1111
#define IDC_STATIC_ICON1                1113
#define IDC_STATIC_ICON2                1114
#define IDC_STATIC_ICON3                1115
#define IDC_STATIC_ICON4                1116
#define IDC_EDIT_TITLE                  1117
#define IDC_STATIC_ICON5                1118
#define IDC_STATIC_SHOW                 1118
#define IDC_EDIT4                       1119
#define IDC_EDIT5                       1120
#define IDC_BUTTON5                     1121
#define IDC_FILE_PATH                   1122
#define ID_LOCAL_TOOLBAR                0x5001
#define ID_REMOTE_TOOLBAR               0x5002
#define ID_APP_PWD                      32771
#define IDM_START                       32771
#define IDM_FILEMANAGER                 32772
#define IDM_STOP                        32772
#define IDM_SHUTDOWN                    32773
#define IDM_DELETE_LIST                 32773
#define IDM_REBOOT                      32774
#define IDM_TRANSFER                    32775
#define IDM_RENAME                      32776
#define IDM_DELETE                      32777
#define IDM_NEWFOLDER                   32778
#define IDM_PROPERTY                    32779
#define IDT_LOCAL_PREV                  32780
#define IDT_LOCAL_COPY                  32781
#define IDT_LOCAL_DELETE                32782
#define IDT_LOCAL_VIEW                  32783
#define IDT_LOCAL_NEWFOLDER             32784
#define IDT_REMOTE_PREV                 32790
#define IDT_REMOTE_COPY                 32791
#define IDT_REMOTE_DELETE               32792
#define IDT_REMOTE_NEWFOLDER            32793
#define IDT_REMOTE_VIEW                 32794
#define IDT_REMOTE_STOP                 32795
#define IDT_LOCAL_STOP                  32797
#define IDM_LOCAL_BIGICON               32798
#define IDM_LOCAL_SMALLICON             32799
#define IDM_LOCAL_LIST                  32800
#define IDM_LOCAL_REPORT                32801
#define IDM_REMOTE_BIGICON              32802
#define IDM_REMOTE_SMALLICON            32803
#define IDM_REMOTE_LIST                 32804
#define IDM_REMOTE_REPORT               32805
#define IDM_SCREENSPY                   32806
#define IDM_DOWNEXEC                    32807
#define IDM_WEBCAM                      32808
#define IDM_REMOVE                      32809
#define IDM_KEYBOARD                    32810
#define IDM_REFRESH                     32811
#define IDM_SYSTEM                      32812
#define IDM_KILLPROCESS                 32813
#define IDM_REFRESHPSLIST               32814
#define IDM_REMOTESHELL                 32815
#define IDM_LOGOFF                      32818
#define IDM_SELECT_ALL                  32820
#define IDM_UNSELECT_ALL                32821
#define IDM_OPEN_URL_SHOW               32825
#define IDM_OPEN_URL_HIDE               32827
#define IDM_CLEANEVENT                  32828
#define IDM_HIDE                        32829
#define IDM_SHOW                        32830
#define IDM_EXIT                        32831
#define IDM_RENAME_REMARK               32832
#define IDM_UPDATE_SERVER               32833
#define IDM_LOCAL_OPEN                  32834
#define IDM_REMOTE_OPEN_SHOW            32836
#define IDM_REMOTE_OPEN_HIDE            32837
#define IDM_AUDIO_LISTEN                32838
#define IDM_DISCONNECT                  32840
#define ID_BUTTON32841                  32841
#define IDB_EXIT                        32842
#define IDB_SUBMIT                      32842
#define ID                              32842
#define IDB_ABOUT_TERMINATE             32843
#define IDT_CHANGESKIN                  32843
#define IDT_UPDATEHOST                  32843
#define IDT_SCREENSPY                   32844
#define IDT_FILEMANEGER                 32845
#define IDT_FILEMANEGERS                32845
#define IDT_KETBOADSPY                  32846
#define IDT_COMMANDSHELL                32847
#define IDT_SYSTEMMANAGER               32848
#define IDT_VEDIOSPY                    32849
#define IDT_SOUNDSPY                    32850
#define IDT_CREATESERVER                32851
#define IDT_ABOUTTERMINATE              32852
#define IDT_EXITPROCESS                 32853
#define IDT_DDOSATTACK                  32854
#define IDT_TEMP                        32855
#define IDT_TOOLS                       32855
#define IDT_SIFTHOST                    32856
#define IDM_BATCH                       32857
#define IDM_STARTBATCH                  32858
#define IDM_STOPBATCH                   32859
#define IDM_DELETEBATCH                 32860
#define IDM_CONFIGING                   32861
#define IDM_REVERSE                     32862
#define IDM_SELECT_XP                   32863
#define IDM_SELECT_SERVER               32864
#define IDM_CUSTOM_SELECT               32865
#define IDM_COUNTHOST                   32867
#define IDM_DDOS                        32868
#define IDM_OPEN3389                    32869
#define IDM_SELECT_WIN7                 32870
#define IDM_CHECKUPDATE                 32871
#define IDM_OFFICAIL                    32872
#define IDT_TEMP1                       32873
#define IDT_TEMP2                       32874
#define IDM_DELETE_REPEAT               32875
#define IDM_SENDMESSAGE                 32876
#define IDM_PLUGIN                      32877
#define IDM_PLUGIN_START                32878
#define IDM_PLUGIN_END                  32879
#define IDM_PLUGIN_DELETE               32880
#define IDM_REFURBISH                   32881
#define ID_opendaili                    32882
#define IDM_ADD_USER                    32883
#define IDT_TEMP4                       32884
#define IDT_TEMP5                       32885
#define ID_open3389                     32886
#define IDM_GXIP                        32887
#define ID_ADD_SKIN                     32888
#define ID_BLACK_SKIN                   32889
#define ID_BLUE_SKIN                    32890
#define ID_RED_SKIN                     32891
#define ID_SILVER_SKIN                  32892
#define ID_DEL_SKIN                     32893
#define ID_CHANGE_SKIN                  32894
#define ID_DELETE_ITEM                  32907
#define ID_EMPTY_ITEM                   32908
#define ID_SAVE_LOG                     32909
#define ID_COPY                         32910
#define ID_STAUTSTIP                    59394
#define ID_STAUTSSPEED                  59395
#define ID_STAUTSPORT                   59396
#define ID_STAUTSCOUNT                  59397
#define ID_STAUTSWEICOME                59398

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32895
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
